- name: MobileComm network installation
  hosts: all
  tasks:
    - name: Debug the OS distribution  
      debug:
        msg: "{{ hostvars[inventory_hostname].ansible_distribution }}"
    - name: Debug the OS major version
      debug:
        msg: "{{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
    - name: Debug the OS version
      debug:
        msg: "{{ hostvars[inventory_hostname].ansible_distribution_version }}"
    - name: Debug the ansible_virtualization_role
      debug:
        msg: This is a Virtual Host
      when: ansible_virtualization_role == 'guest' 
      ignore_errors: yes
    - name: Debug the ansible_virtualization_role
      debug:
        msg: This is a Physical Host
      when: ansible_virtualization_role == 'host'
      ignore_errors: yes
    - command: 'lsblk -lno NAME'
      register: results
    - name: Create list of block devices
      set_fact:
        block_devices: "{{ block_devices|default([]) + [ item ] }}"
      loop: "{{ results.stdout_lines }}"
    - debug:
        var: block_devices
